# Generated by Django 5.1.4 on 2024-12-29 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('condition_prebook_event', 'Dieser Nutzer darf aus z.B. medizinischen Gründen einen Termin vor der offiziellen Buchungsphasen anfragen.'), ('book_double_event', 'Dieser Nutzer darf aus z.B. medizinischen Gründen auch Doppeltermine bei einer Lehrkraft anfragen.')], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
    ]
