# Generated by Django 5.1.4 on 2024-12-29 23:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseeventgroup',
            name='lead_status_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dayeventgroup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dayeventgroup',
            name='lead_status_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead_status_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teachereventgroup',
            name='lead_status_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
