# Generated by Django 5.1.4 on 2024-12-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_baseeventgroup_lead_status_last_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventchangeformula',
            name='date',
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
    ]
