# Generated by Django 5.1.2 on 2025-01-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventchangeformula_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchangeformula',
            name='connected_events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.DeleteModel(
            name='EventChangeLogs',
        ),
    ]
