# Generated by Django 5.1.2 on 2025-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventchangeformula_connected_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchangeformula',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventchangeformula',
            name='reversable',
            field=models.BooleanField(default=False),
        ),
    ]
