# Generated by Django 5.1.2 on 2025-01-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventchangeformula_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='base_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.baseeventgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.dayeventgroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='teacher_event_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.teachereventgroup'),
        ),
    ]
