version: '3'

services:
  redis:
    image: redis:latest
    container_name: rd01
    ports:
     - '6379:6379'

  django:
    container_name: dj01
    image: djangoelternsprechtag:latest
    environment:
      - DB_HOST=db
      - DB_NAME=elternsprechtag
      - DB_USERNAME=elternsprechtag
      - DB_PASSWORD=jhg2023
    ports:
      - '8000:8000'
    links: 
      - redis
    depends_on:
      - db
      - redis

  db:
    image: lscr.io/linuxserver/mariadb
    container_name: elternsprechtag_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=jhg2023
      - TZ=Europe/London
      - MYSQL_DATABASE=elternsprechtagapp
      - MYSQL_USER=elternsprechtag
      - MYSQL_PASSWORD=jhg2023
    volumes:
      - /path/to/data:/config
    restart: unless-stopped

  celery:
    image: djangoelternsprechtag:latest
    command: celery -A elternsprechtag worker -B --loglevel=DEBUG
    links:
      - redis
    depends_on:
      - redis