# Generated by Django 5.1.4 on 2024-12-29 22:55

import dashboard.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_start', models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann alle Eltern Termine anfragen können.')),
                ('lead_inquiry_start', models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann Anfragen der Lehrkräfte beantwortet werden können.')),
                ('event_duration', models.DurationField(default=datetime.timedelta(seconds=450), help_text='Hier legen Sie die allgemeine Länge eines Termins fest. Sie bezieht sich auf alle mit dieser Funktion erstellten Termine.')),
                ('min_event_seperation', models.DurationField(default=datetime.timedelta(seconds=300), help_text='Hier können Sie den Abstand zwischen zwei Terminen festlegen. Sie sollten etwas Zeit zum Wechseln der Räume usw. einplanen.')),
                ('event_in_seperation_bookable', models.BooleanField(default=False)),
                ('impressum', models.URLField(default='')),
                ('keep_events', models.DurationField(default=datetime.timedelta(days=30))),
                ('delete_events', models.BooleanField(default=True)),
                ('keep_student_changes', models.DurationField(default=datetime.timedelta(days=60))),
                ('delete_student_changes', models.BooleanField(default=False)),
                ('keep_announcements', models.DurationField(default=datetime.timedelta(days=30))),
                ('delete_announcements', models.BooleanField(default=True)),
                ('keep_event_change_formulas', models.DurationField(default=datetime.timedelta(days=30))),
                ('delete_event_change_formulas', models.BooleanField(default=False)),
                ('iquiry_bahvior', models.JSONField(default=dashboard.models.SiteSettings.get_default_inquiry_behavior)),
            ],
            options={
                'verbose_name': 'Seiteneinstellungen',
                'verbose_name_plural': 'Seiteneinstellungen',
            },
        ),
    ]
