# Generated by Django 4.1 on 2022-10-05 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.IntegerField(blank=True, default=None, null=True)),
                ('occupied', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, default=None, limit_choices_to={'role': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_parent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ManyToManyField(blank=True, default=None, to='authentication.student')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_start', models.DateField(default=django.utils.timezone.now)),
                ('lead_inquiry_start', models.DateField(default=django.utils.timezone.now)),
                ('event_duration', models.DurationField(default=datetime.timedelta(0))),
                ('time_start', models.TimeField(default=django.utils.timezone.now)),
                ('time_end', models.TimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Anfrage zur Buchung eines Termins (Lehrer->Eltern)'), (1, 'Anfrage zur Bestätigung eines Termins (Eltern->Lehrer)')], default=0)),
                ('reason', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.event')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requester', to=settings.AUTH_USER_MODEL)),
                ('respondent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_respondent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
