# Generated by Django 5.1.4 on 2024-12-30 01:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.IntegerField(choices=[(0, 'Neue Buchungsanfrage'), (1, 'Terminabsage'), (2, 'Systembenachrichtigung')], default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('action_link', models.TextField(blank=True, null=True)),
                ('action_name', models.CharField(blank=True, max_length=200, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
            },
        ),
    ]
