# Generated by Django 4.0.4 on 2022-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_event_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
