# Generated by Django 4.0.4 on 2022-08-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_alter_customuser_email_alter_customuser_first_name_and_more'),
        ('dashboard', '0006_alter_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('possible_events', models.ManyToManyField(limit_choices_to={'occupied': False}, to='dashboard.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
