# Generated by Django 5.1.1 on 2024-10-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_alter_eventchangeformula_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='id_uuid',
        ),
    ]
