# Generated by Django 5.1.1 on 2024-10-24 10:30

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("myapp", "MyModel")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0082_rename_id_event_id_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="id_uuid",
        ),
        migrations.AddField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
