# Generated by Django 5.1.1 on 2024-10-31 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('A', 'Automatically created backup'), ('M', 'Manually created backup'), ('U', 'User-uploaded backup')], default='A', max_length=1)),
                ('backup_file', models.FilePathField()),
                ('backup_directories', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('keep_backup', models.BooleanField(default=True)),
                ('validation_hash', models.CharField(max_length=40, null=True, unique=True)),
                ('external', models.BooleanField(default=False, help_text='Dies ist eine Angabe darüber, ob das Backup von einem Externen Server stammt oder extern modifiziert wurde.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': (('can_restore_backup', 'Kann Backup wiederherstellen'), ('can_add_backup', 'Kann Backup erstellen')),
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=200)),
                ('module', models.TextField(null=True)),
                ('output', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
