# Generated by Django 5.0.6 on 2024-07-21 22:12

import custom_backup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAppsConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.BooleanField()),
                ('referenced_app', models.IntegerField(choices=custom_backup.models.BackupAppsConfigs.get_choices)),
            ],
        ),
        migrations.CreateModel(
            name='BackupModelConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.BooleanField(default=True)),
                ('referenced_model', models.IntegerField()),
            ],
        ),
    ]
