# Generated by Django 5.0.6 on 2024-07-21 22:20

import custom_backup.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupmodelconfigs',
            name='corresponding_app',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='custom_backup.backupappsconfigs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupappsconfigs',
            name='referenced_app',
            field=models.IntegerField(choices=custom_backup.models.BackupAppsConfigs.get_choices, unique=True),
        ),
    ]
