# Generated by Django 5.0.6 on 2024-07-21 22:53

import custom_backup.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0002_backupmodelconfigs_corresponding_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupappsconfigs',
            name='app_label',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='backupmodelconfigs',
            name='model_label',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='backupmodelconfigs',
            name='referenced_model',
            field=models.IntegerField(choices=custom_backup.models.BackupModelConfigs.get_choices, unique=True),
        ),
    ]
