# Generated by Django 5.0.6 on 2024-07-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0003_backupappsconfigs_app_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupappsconfigs',
            name='app_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='backupmodelconfigs',
            name='model_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
