# Generated by Django 5.0.6 on 2024-07-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0004_alter_backupappsconfigs_app_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupmodelconfigs',
            name='depends_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_backup.backupmodelconfigs'),
        ),
    ]
